version: '3.8'
services:
  php:
    build:
      context: ./back
    ports:
      - "80:80"
    volumes:
      - ./back:/var/www/html
    networks:
      - app-network

  vue:
    build:
      context: ./board
    ports:
      - "3000:80"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
