version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - VUE_APP_API_URL=https://kanban-website-production.up.railway.app

networks:
  app-network:
    driver: bridge
