services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:8080"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "3306:3306"
      - "81:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
